# ------------------------------------------------------------------------------------------------ #
[versions]
## --- Plugins and more general stuff --- ##
#noinspection UnusedVersionCatalogEntry
jacoco = "0.8.14"
detekt = "1.23.8"

## --- Build Config and SDK --- ##
#noinspection UnusedVersionCatalogEntry
build-sdk-min = "20"
#noinspection UnusedVersionCatalogEntry
build-sdk-compile = "36"
#noinspection UnusedVersionCatalogEntry
build-tools = "36.1.0"

## JetBrains
jetbrains-kotlin = "2.3.10"
jetbrains-dokka = "2.1.0"
jetbrains-kover = "0.9.6"
jetbrains-coroutines = "1.10.2"

## AndroidX
androidx-plugin = "9.0.0"

## Tools
ktlint = "14.0.1"
vanniktech-publish = "0.36.0"

# ------------------------------------------------------------------------------------------------ #
[libraries]
## JetBrains
jetbrains-dokka = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "jetbrains-dokka" }
jetbrains-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "jetbrains-kotlin" }
jetbrains-multiplatform = { module = "org.jetbrains.kotlin.multiplatform:org.jetbrains.kotlin.multiplatform.gradle.plugin", version.ref = "jetbrains-kotlin" }
jetbrains-kover = { module = "org.jetbrains.kotlinx:kover-gradle-plugin", version.ref = "jetbrains-kover" }
jetbrains-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "jetbrains-coroutines" }
jetbrains-kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "jetbrains-kotlin" }

## Androidx
androidx-library = { module = "com.android.kotlin.multiplatform.library:com.android.kotlin.multiplatform.library.gradle.plugin", version.ref = "androidx-plugin" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.7.1" }
androidx-recycler = { module = "androidx.recyclerview:recyclerview", version = "1.4.0" }
androidx-window = { module = "androidx.window:window", version = "1.5.1" }
androidx-security = { module = "androidx.security:security-crypto-ktx", version = "1.1.0" }
androidx-startup = { module = "androidx.startup:startup-runtime", version = "1.2.0" }
androidx-constraint = { module = "androidx.constraintlayout:constraintlayout", version = "2.2.1" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime", version = "2.10.0" }

## Arch Toolkit
arch-lumber = { module = "io.github.matheus-corregiari:arch-lumber", version = "1.0.2" }

## Tools
detekt = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
ktlint = { module = "org.jlleitschuh.gradle.ktlint:org.jlleitschuh.gradle.ktlint.gradle.plugin", version.ref = "ktlint" }
vanniktech-publish = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "vanniktech-publish" }

# ------------------------------------------------------------------------------------------------ #
[plugins]
## Nothing Here Yet!

# ------------------------------------------------------------------------------------------------ #
[bundles]
## Nothing Here Yet!
